# Generated by Django 4.1.5 on 2023-03-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_about_user_phone_user_start_date_user_wishlist_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billingaddress",
            name="country",
        ),
        migrations.RemoveField(
            model_name="user",
            name="about",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
        migrations.AddField(
            model_name="billingaddress",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
