# Generated by Django 4.1.5 on 2023-05-09 09:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_delete_cartitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
    ]
