# Generated by Django 4.1.2 on 2023-02-05 09:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_alter_category_options_alter_product_options"),
        ("store", "0007_alter_popular_products_product"),
    ]

    operations = []
