# Generated by Django 4.1.2 on 2023-02-05 09:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0008_merge_20230205_0914"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-created", "order"]},
        ),
    ]
