# Generated by Django 4.1.5 on 2023-03-10 00:34

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_billingaddress_country_remove_user_about_and_more"),
        ("store", "0009_alter_category_options_alter_product_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="popular_products",
            name="product",
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["order"], "verbose_name_plural": "categories"},
        ),
        migrations.AlterModelOptions(
            name="option",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["order"]},
        ),
        migrations.RemoveIndex(
            model_name="category",
            name="store_categ_name_1278fd_idx",
        ),
        migrations.RemoveField(
            model_name="order",
            name="building_number",
        ),
        migrations.RemoveField(
            model_name="order",
            name="city",
        ),
        migrations.RemoveField(
            model_name="order",
            name="country",
        ),
        migrations.RemoveField(
            model_name="order",
            name="email",
        ),
        migrations.RemoveField(
            model_name="order",
            name="fast_delivery",
        ),
        migrations.RemoveField(
            model_name="order",
            name="street_number",
        ),
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.RemoveField(
            model_name="order",
            name="zone_number",
        ),
        migrations.AddField(
            model_name="option",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="",
                editable=False,
                max_length=100,
                populate_from="name",
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.billingaddress",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="is_popular",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="option",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash_on_delivery", "Cash on delivery"),
                    ("online_payment", "Online Payment"),
                ],
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Unpaid"),
                    ("paid", "Paid"),
                    ("pending", "Pending"),
                    ("canceled", "Canceled"),
                    ("pending_refund", "Pending refund"),
                    ("refunded", "Refunded"),
                    ("delivered", "Delivered"),
                ],
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="store.order",
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["order"], name="store_categ_order_bd9145_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["-created"], name="store_order_created_ddd900_idx"
            ),
        ),
        migrations.DeleteModel(
            name="Popular_Products",
        ),
    ]
