# Generated by Django 4.1.5 on 2023-03-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0010_remove_popular_products_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="img",
            field=models.ImageField(blank=True, upload_to="category"),
        ),
        migrations.AlterField(
            model_name="option",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="img",
            field=models.ImageField(upload_to="products"),
        ),
    ]
