# Generated by Django 4.1.5 on 2023-03-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0011_alter_category_img_alter_option_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="option",
            name="price",
            field=models.FloatField(),
        ),
    ]
