# Generated by Django 4.1.5 on 2023-04-01 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0014_color_size_remove_option_product_and_more"),
        ("users", "0004_alter_cartitem_unique_together_remove_user_cart_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Option",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="color",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.color",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitem",
            name="size",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="store.size"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="available_colors",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="store.color"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="available_sizes",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="store.size"
            ),
        ),
    ]
