# Generated by Django 4.1.5 on 2023-05-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvailableProducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Available Products", max_length=100),
                ),
                (
                    "description",
                    models.TextField(
                        default="Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum, illum optio eum magni quidem dolorum accusantium omnis"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="defaults/shop-bg.jpg", upload_to="shop_page"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
