# Generated by Django 4.1.5 on 2023-05-08 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "website",
            "0002_remove_phonenum_tile_calltile_phone1_calltile_phone2_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
            ],
        ),
    ]
