# Generated by Django 4.1.5 on 2023-05-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_contactmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(
                        default="defaults/shop-bg.jpg", upload_to="defaults"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum, illum optio eum magni quidem dolorum accusantium omnis"
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
