# Generated by Django 4.1.5 on 2023-05-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_rename_newarrivals_newarrivalssection_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutUsHero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Hero_Section", max_length=100)),
                (
                    "description",
                    models.TextField(
                        default="Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum, illum optio eum magni quidem dolorum accusantium omnis"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="defaults/shop-bg.jpg", upload_to="shop_page"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AboutUsPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="About_Us", max_length=100)),
                (
                    "description",
                    models.TextField(
                        default="Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum, illum optio eum magni quidem dolorum accusantium omnis"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="defaults/shop-bg.jpg", upload_to="shop_page"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Founder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "description",
                    models.TextField(
                        default="Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum, illum optio eum magni quidem dolorum accusantium omnis"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="defaults/founder.png", upload_to="founder"
                    ),
                ),
                ("face_icon", models.URLField(null=True)),
                ("insta_icon", models.URLField(null=True)),
                ("twit_icon", models.URLField(null=True)),
            ],
        ),
    ]
