# Generated by Django 4.1.5 on 2023-05-08 15:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=ckeditor.fields.RichTextField(
                default="Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum, illum optio eum magni quidem dolorum accusantium omnis"
            ),
        ),
    ]
