# Generated by Django 4.1.5 on 2023-05-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_alter_blog_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(default="defaults/hero.png", upload_to="defaults"),
        ),
    ]
