# Generated by Django 4.1.5 on 2023-05-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_aboutustile_delete_aboutuspage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutushero",
            name="image",
            field=models.ImageField(default="defaults/hero.png", upload_to="defaults"),
        ),
        migrations.AlterField(
            model_name="aboutustile",
            name="image",
            field=models.ImageField(default="defaults/hero.png", upload_to="defaults"),
        ),
    ]
